CREATE INDEX `announcements_created_by_idx` ON `announcements` (`created_by_user_id`);--> statement-breakpoint
CREATE INDEX `card_drops_game_idx` ON `card_drops` (`game_id`);--> statement-breakpoint
CREATE INDEX `card_drops_deck_idx` ON `card_drops` (`deck_id`);--> statement-breakpoint
CREATE INDEX `cards_deck_idx` ON `cards` (`deck_name`);--> statement-breakpoint
CREATE INDEX `feature_flags_updated_by_idx` ON `feature_flags` (`updated_by_user_id`);--> statement-breakpoint
CREATE INDEX `friendships_user2_idx` ON `friendships` (`user2_id`);--> statement-breakpoint
CREATE INDEX `friendships_inviter_idx` ON `friendships` (`inviter_id`);--> statement-breakpoint
CREATE INDEX `game_eliminations_game_idx` ON `game_eliminations` (`game_id`);--> statement-breakpoint
CREATE INDEX `game_eliminations_user_idx` ON `game_eliminations` (`eliminated_user_id`);--> statement-breakpoint
CREATE INDEX `game_itemized_score_categories_game_idx` ON `game_itemized_score_categories` (`game_id`);--> statement-breakpoint
CREATE INDEX `game_itemized_score_entries_game_idx` ON `game_itemized_score_entries` (`game_id`);--> statement-breakpoint
CREATE INDEX `game_itemized_score_entries_round_idx` ON `game_itemized_score_entries` (`game_round_id`);--> statement-breakpoint
CREATE INDEX `game_itemized_score_entries_user_idx` ON `game_itemized_score_entries` (`user_id`);--> statement-breakpoint
CREATE INDEX `game_itemized_score_entries_category_idx` ON `game_itemized_score_entries` (`category_id`);--> statement-breakpoint
CREATE INDEX `game_join_requests_resolved_by_idx` ON `game_join_requests` (`resolved_by_user_id`);--> statement-breakpoint
CREATE INDEX `game_player_rank_results_user_idx` ON `game_player_rank_results` (`user_id`);--> statement-breakpoint
CREATE INDEX `game_player_rank_results_rank_config_idx` ON `game_player_rank_results` (`rank_config_id`);--> statement-breakpoint
CREATE INDEX `game_players_game_idx` ON `game_players` (`game_id`);--> statement-breakpoint
CREATE INDEX `game_players_user_idx` ON `game_players` (`user_id`);--> statement-breakpoint
CREATE INDEX `game_result_placements_user_idx` ON `game_result_placements` (`user_id`);--> statement-breakpoint
CREATE INDEX `game_round_scores_game_round_idx` ON `game_round_scores` (`game_round_id`);--> statement-breakpoint
CREATE INDEX `game_round_scores_user_idx` ON `game_round_scores` (`user_id`);--> statement-breakpoint
CREATE INDEX `game_rounds_game_idx` ON `game_rounds` (`game_id`);--> statement-breakpoint
CREATE INDEX `game_title_reward_deck_idx` ON `game_title` (`reward_deck_name`);--> statement-breakpoint
CREATE INDEX `game_title_created_by_idx` ON `game_title` (`created_by_user_id`);--> statement-breakpoint
CREATE INDEX `game_title_merged_into_idx` ON `game_title` (`merged_into_game_title_id`);--> statement-breakpoint
CREATE INDEX `game_winners_user_idx` ON `game_winners` (`user_id`);--> statement-breakpoint
CREATE INDEX `games_game_title_idx` ON `games` (`game_title_id`);--> statement-breakpoint
CREATE INDEX `games_creator_idx` ON `games` (`creator_id`);--> statement-breakpoint
CREATE INDEX `games_paused_next_user_idx` ON `games` (`paused_next_user_id`);--> statement-breakpoint
CREATE INDEX `invitations_inviter_idx` ON `invitations` (`inviter_user_id`);--> statement-breakpoint
CREATE INDEX `invitations_invitee_idx` ON `invitations` (`invitee_user_id`);--> statement-breakpoint
CREATE INDEX `invitations_guest_idx` ON `invitations` (`guest_user_id`);--> statement-breakpoint
CREATE INDEX `invitations_accepted_by_idx` ON `invitations` (`accepted_by_user_id`);--> statement-breakpoint
CREATE INDEX `player_rank_configs_created_by_idx` ON `player_rank_configs` (`created_by_user_id`);--> statement-breakpoint
CREATE INDEX `user_game_title_game_title_idx` ON `user_game_title` (`game_title_id`);--> statement-breakpoint
CREATE INDEX `user_game_title_source_game_idx` ON `user_game_title` (`source_game_id`);--> statement-breakpoint
CREATE INDEX `user_game_title_acquired_from_idx` ON `user_game_title` (`acquired_from_user_id`);--> statement-breakpoint
CREATE INDEX `user_game_title_prefs_game_title_idx` ON `user_game_title_preferences` (`game_title_id`);--> statement-breakpoint
CREATE INDEX `user_game_title_settings_game_title_idx` ON `user_game_title_settings` (`game_title_id`);--> statement-breakpoint
CREATE INDEX `users_merged_into_idx` ON `users` (`merged_into_user_id`);--> statement-breakpoint
CREATE INDEX `users_created_by_idx` ON `users` (`created_by_user_id`);